- Whenever you need the gradient of any variable you can set paramter requires_grad= True
- if any variable that has requires_grad = True is used in any computation other variables are also added to computaional graph.

- There are following ways you can avaoid the variable to be added in computational graph
    - detach
    - required_grad = False
    - torch.no_grad
    
- you can calculate the backprop on scalar value else have to provide the vector of same size

- you have to empty the gradient after every iteration because value are keep adding. 
  Same you will see with the optimizer also. Before any optimizer step you have to empty the gradients

In [1]:
import torch

In [2]:
a = torch.randn(3) ## cannot calculate the gradient
print(a)

tensor([1.4275, 1.7497, 0.0345])


In [3]:
a = torch.randn(3, requires_grad = True)  ## can calculate the gradient
print(a)

tensor([-0.1067,  1.0230, -0.5194], requires_grad=True)


In [4]:
## every variables have grad fn functions
a = torch.randn(3, requires_grad = True)
b = a +1 
c = 3*b
z = torch.mean(c)

print(a)
print(b)
print(c)
print(z)

tensor([-1.4927,  0.9047,  1.4927], requires_grad=True)
tensor([-0.4927,  1.9047,  2.4927], grad_fn=<AddBackward0>)
tensor([-1.4782,  5.7141,  7.4780], grad_fn=<MulBackward0>)
tensor(3.9046, grad_fn=<MeanBackward0>)


In [5]:
## you can avoid : using requires_grad = False
a = torch.randn(3, requires_grad = True)
print(a)

a.requires_grad_(False)
print(a)

tensor([-0.6776,  0.0348, -1.0934], requires_grad=True)
tensor([-0.6776,  0.0348, -1.0934])


In [6]:
## you can avoid : using detach
a = torch.randn(3, requires_grad = True)
print(a)


b = a.detach() + 1
print(b)

tensor([ 0.1064, -0.3573,  0.6710], requires_grad=True)
tensor([1.1064, 0.6427, 1.6710])


In [7]:
## you can avoid : using no grad
a = torch.randn(3, requires_grad = True)
print(a)

with torch.no_grad():
    b = a +1
    print(b)

tensor([-0.8097,  0.4454,  0.0533], requires_grad=True)
tensor([0.1903, 1.4454, 1.0533])


## Check the gradient

In [8]:
a = torch.randn(3,requires_grad = True)

b = a+1
z = 3*b
z = z.mean()  
print("z: ",z) ## scalar value calculate the gradient

print("Before : ", a.grad)
z.backward()
print("After : ", a.grad)

z:  tensor(1.7423, grad_fn=<MeanBackward0>)
Before :  None
After :  tensor([1., 1., 1.])


In [9]:
## if z is not scalar you will get error
a = torch.randn(3,requires_grad = True)

b = a+1
z = 3*b
print("z: ",z) ## scalar value calculate the gradient

try:
    z.backward()
except:
    print("Error: z is not scalar or provide the vector")

z:  tensor([2.7031, 8.9237, 3.2994], grad_fn=<MulBackward0>)
Error: z is not scalar or provide the vector


In [10]:
## provide the vector to calculate the gradient
a = torch.randn(3,requires_grad = True)

b = a+1
z = 3*b
v = torch.tensor([1,1,1])
z.backward(v)
print(a.grad)

tensor([3., 3., 3.])


In [11]:
## Value are not rights for gradient
w = torch.randn(3, requires_grad = True)

for epoch in range(3):
    model_output = (3*w).sum()
    model_output.backward()
    print(w.grad)

tensor([3., 3., 3.])
tensor([6., 6., 6.])
tensor([9., 9., 9.])


In [12]:
## empty gradient before every run
w = torch.randn(3, requires_grad = True)

for epoch in range(3):
    model_output = (3*w).sum()
    
    model_output.backward()
    print(w.grad)
    w.grad.zero_()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
