In [1]:
import torch
import numpy as np

    Everything is in pytorch is a tensor. 
    Tensor are similar to numpy objects but it can run on GPU also.
    
    
## Ways to create tensor
    - from python objects
    - from numpy objects
    - using inbuilt functions

### using python objects

In [2]:
array_list = [1,2,3]
a = torch.tensor(array_list)
print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


## using numpy objects

In [3]:
numpy_array= np.array([[1,2,3],[4,5,6]])
print(numpy_array)

tensor_array = torch.from_numpy(numpy_array)
print(type(tensor_array))
print(tensor_array)

[[1 2 3]
 [4 5 6]]
<class 'torch.Tensor'>
tensor([[1, 2, 3],
        [4, 5, 6]])


## using inbuilt functions

In [4]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
torch.full((3,2),5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [7]:
torch.randn(3,2)

tensor([[ 1.0275,  0.2820],
        [-0.2277, -1.7773],
        [ 0.5538,  1.5500]])

## Tensor Operation

    Below are the ways to add tensor in pytorch.similary you can do for other tensor also.
    
        - torch.add(a,b)
        - a.add_(b) : underscore shows the inplace update in pytorch. final value will be in a
        - a + b

In [8]:
a = torch.randn(3,2)
b = torch.randn(3,2)

print("Add : ", a+b)
print("Sub : ", a-b)
print("Mul : ",a*b)
print("Div : ",a/b)

Add :  tensor([[ 2.3413,  1.3995],
        [ 0.9806, -0.7820],
        [-0.5862,  0.7202]])
Sub :  tensor([[-1.0038,  1.0069],
        [-1.1790, -0.9375],
        [ 0.7772,  0.3816]])
Mul :  tensor([[ 1.1185,  0.2362],
        [-0.1071, -0.0669],
        [-0.0651,  0.0933]])
Div :  tensor([[  0.3998,   6.1282],
        [ -0.0919, -11.0541],
        [ -0.1401,   3.2544]])


In [9]:
## matrix multiplication 
a = torch.randn(3,2)
b = torch.randn(2,3)
print(torch.matmul(a,b))

tensor([[-1.4572, -2.1233, -1.6327],
        [ 0.6659,  4.5691,  4.0364],
        [-0.7165, -3.6468, -3.1825]])


## Properties of tensor
    - shape or size : length of tensor
    - view : used to reshape the tensor
    - dtype : give the info about data type
    - type : will tell you about is it tensor ?

In [10]:
a = torch.randn(3,2)
print(f"Size : {a.size()}, shape : {a.shape}")
print(f"type : {type(a)}")
print(f"dtype : {a.dtype}")

Size : torch.Size([3, 2]), shape : torch.Size([3, 2])
type : <class 'torch.Tensor'>
dtype : torch.float32


In [11]:
a = torch.randn(8,2)
print(a.shape)
a = a.view(4,4)
print(a.shape)
print(a)

torch.Size([8, 2])
torch.Size([4, 4])
tensor([[ 1.1907,  0.7856, -0.9121, -1.3902],
        [-0.5715,  0.0470, -0.9282, -1.2781],
        [ 0.0884, -0.7333,  0.0650, -0.9102],
        [-0.2615, -0.1394,  0.6720, -0.9572]])


## Type casting

In [12]:
a = torch.tensor([1,2,3], dtype = torch.float16)
print(a.dtype)

a = a.type(torch.float32)
print(a.dtype)

torch.float16
torch.float32


## Reduce dimension of tensor

In [13]:
a = torch.randn(1,2,3)
print(a.shape)

a = torch.squeeze(a)
print(a.shape)

torch.Size([1, 2, 3])
torch.Size([2, 3])


## Expand the dimension of tensor

In [14]:
a = torch.randn(2,3)
print(a.shape)

b = torch.unsqueeze(a,0)
print(b.shape)

b = torch.unsqueeze(a,1)
print(b.shape)

torch.Size([2, 3])
torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
