In [7]:
import torch
import numpy as np

    Everything is in pytorch is a tensor. 
    Tensor are similar to numpy objects but it can run on GPU also.
    
    
## Ways to create tensor
    - from python objects
    - from numpy objects
    - using inbuilt functions

### using python objects

In [6]:
array_list = [1,2,3]
a = torch.tensor(array_list)
print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


## using numpy objects

In [8]:
numpy_array= np.array([[1,2,3],[4,5,6]])
print(numpy_array)

tensor_array = torch.from_numpy(numpy_array)
print(type(tensor_array))
print(tensor_array)

[[1 2 3]
 [4 5 6]]
<class 'torch.Tensor'>
tensor([[1, 2, 3],
        [4, 5, 6]])


## using inbuilt functions

In [9]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
torch.full((3,2),5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [13]:
torch.randn(3,2)

tensor([[-0.5042,  0.6372],
        [-0.5248, -1.1229],
        [ 1.7663, -0.5275]])

## Tensor Operation

    Below are the ways to add tensor in pytorch.similary you can do for other tensor also.
    
        - torch.add(a,b)
        - a.add_(b) : underscore shows the inplace update in pytorch. final value will be in a
        - a + b

In [22]:
a = torch.randn(3,2)
b = torch.randn(3,2)

print("Add : ", a+b)
print("Sub : ", a-b)
print("Mul : ",a*b)
print("Div : ",a/b)

Add :  tensor([[ 0.1198,  1.4157],
        [ 1.8241, -0.1640],
        [ 0.4625,  2.6899]])
Sub :  tensor([[-1.4164,  1.6456],
        [ 0.5987,  0.6548],
        [-1.8249,  0.1684]])
Mul :  tensor([[-0.4980, -0.1760],
        [ 0.7422, -0.1005],
        [-0.7791,  1.8019]])
Div :  tensor([[ -0.8441, -13.3149],
        [  1.9773,  -0.5994],
        [ -0.5956,   1.1335]])


In [23]:
## matrix multiplication 
a = torch.randn(3,2)
b = torch.randn(2,3)
print(torch.matmul(a,b))

tensor([[-0.7827,  0.3303, -1.7421],
        [ 1.7479,  1.8001, -5.3670],
        [-5.6102, -3.0050,  7.1121]])


## Properties of tensor
    - shape or size : length of tensor
    - view : used to reshape the tensor
    - dtype : give the info about data type
    - type : will tell you about is it tensor ?

In [24]:
a = torch.randn(3,2)
print(f"Size : {a.size()}, shape : {a.shape}")
print(f"type : {type(a)}")
print(f"dtype : {a.dtype}")

Size : torch.Size([3, 2]), shape : torch.Size([3, 2])
type : <class 'torch.Tensor'>
dtype : torch.float32


In [25]:
a = torch.randn(8,2)
print(a.shape)
a = a.view(4,4)
print(a.shape)
print(a)

torch.Size([8, 2])
torch.Size([4, 4])
tensor([[ 2.0450, -0.8634,  0.6867, -0.1030],
        [ 0.0562,  1.0149, -0.9270, -1.1212],
        [-1.4179,  0.9336,  1.4546,  1.1092],
        [-1.0660,  1.8905, -0.5040, -0.7156]])


## Type casting

In [30]:
a = torch.tensor([1,2,3], dtype = torch.float16)
print(a.dtype)

a = a.type(torch.float32)
print(a.dtype)

torch.float16
torch.float32


## Reduce dimension of tensor

In [32]:
a = torch.randn(1,2,3)
print(a.shape)

a = torch.squeeze(a)
print(a.shape)

torch.Size([1, 2, 3])
torch.Size([2, 3])


## Expand the dimension of tensor

In [34]:
a = torch.randn(2,3)
print(a.shape)

b = torch.unsqueeze(a,0)
print(b.shape)

b = torch.unsqueeze(a,1)
print(b.shape)

torch.Size([2, 3])
torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
