In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [2]:
input_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)
input_2d = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype = torch.float)
input_2d_img = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], 
                             [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], 
                             [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]], dtype = torch.float)

In [3]:
input_1d.shape, input_2d.shape, input_2d_img.shape

(torch.Size([10]), torch.Size([2, 5]), torch.Size([3, 3, 10]))

## There are 3 types of convolution operations.

   **1D convolution**
        - majorly used where the input is sequential such as text or audio.
        - Input shape : [batch_size, input_channel, signal_length]
            
   **2D convolution** 
       — majorly used where the input is an image.
       - Input shape : [batch_size, input_channels, input_height, input_width]

   **3D convolution** 
       — majorly used in 3D medical imaging or detecting events in videos.
       
       
#### Output Image Dimension:
    - lower bound of ((n+2p-f)/s) + 1

## 1 D Convolution

In [4]:
input_1d.shape

torch.Size([10])

In [5]:
input_1d.unsqueeze(0).shape, input_1d.unsqueeze(0).unsqueeze(0).shape

(torch.Size([1, 10]), torch.Size([1, 1, 10]))

In [6]:
## shape the shape of input data
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

In [7]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)
print("cnn1d_1: \n")
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 1, 8]) 

tensor([[[1.2412, 1.5913, 1.9413, 2.2914, 2.6415, 2.9915, 3.3416, 3.6917]]],
       grad_fn=<SqueezeBackward1>)


In [8]:
cnn1d_2 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
print("cnn1d_2: \n")
print(cnn1d_2(input_1d).shape, "\n")
print(cnn1d_2(input_1d))

cnn1d_2: 

torch.Size([1, 1, 4]) 

tensor([[[ 0.5194,  0.0885, -0.3425, -0.7734]]], grad_fn=<SqueezeBackward1>)


In [9]:
cnn1d_3 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2, stride=1)
print("cnn1d_3: \n")
print(cnn1d_3(input_1d).shape, "\n")
print(cnn1d_3(input_1d))

cnn1d_3: 

torch.Size([1, 1, 9]) 

tensor([[[-0.4813, -0.6230, -0.7647, -0.9063, -1.0480, -1.1897, -1.3313,
          -1.4730, -1.6147]]], grad_fn=<SqueezeBackward1>)


In [10]:
cnn1d_4 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=1)
print("cnn1d_4: \n")
print(cnn1d_4(input_1d).shape, "\n")
print(cnn1d_4(input_1d))

cnn1d_4: 

torch.Size([1, 5, 8]) 

tensor([[[-0.2785, -0.1557, -0.0328,  0.0901,  0.2129,  0.3358,  0.4587,
           0.5815],
         [ 0.1779,  0.2672,  0.3565,  0.4458,  0.5351,  0.6244,  0.7137,
           0.8031],
         [ 2.0772,  3.1526,  4.2280,  5.3034,  6.3787,  7.4541,  8.5295,
           9.6049],
         [ 1.4643,  1.8987,  2.3331,  2.7675,  3.2019,  3.6363,  4.0707,
           4.5051],
         [ 0.9221,  0.8442,  0.7663,  0.6884,  0.6105,  0.5325,  0.4546,
           0.3767]]], grad_fn=<SqueezeBackward1>)


### Conv1d — Input 2d

In [11]:
input_2d.shape

torch.Size([2, 5])

In [12]:
input_2d

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [13]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [14]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)
print("cnn1d_5: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

cnn1d_5: 

torch.Size([1, 1, 3]) 

tensor([[[3.5274, 4.3024, 5.0774]]], grad_fn=<SqueezeBackward1>)


In [15]:
cnn1d_6 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=2)
print("cnn1d_6: \n")
print(cnn1d_6(input_2d).shape, "\n")
print(cnn1d_6(input_2d))

cnn1d_6: 

torch.Size([1, 1, 2]) 

tensor([[[2.1102, 2.6286]]], grad_fn=<SqueezeBackward1>)


In [16]:
cnn1d_7 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=2, stride=1)
print("cnn1d_7: \n")
print(cnn1d_7(input_2d).shape, "\n")
print(cnn1d_7(input_2d))

cnn1d_7: 

torch.Size([1, 1, 4]) 

tensor([[[-1.0319, -1.1590, -1.2860, -1.4131]]], grad_fn=<SqueezeBackward1>)


In [17]:
cnn1d_8 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1)
print("cnn1d_8: \n")
print(cnn1d_8(input_2d).shape, "\n")
print(cnn1d_8(input_2d))

cnn1d_8: 

torch.Size([1, 5, 3]) 

tensor([[[-1.4778, -1.6075, -1.7373],
         [ 2.5576,  3.2652,  3.9729],
         [-3.3112, -4.1502, -4.9892],
         [ 4.3007,  5.2509,  6.2010],
         [ 1.0870,  1.7911,  2.4953]]], grad_fn=<SqueezeBackward1>)


## 2D Convolution

In [18]:
input_2d_img

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])

In [19]:
input_2d_img.shape

torch.Size([3, 3, 10])

In [20]:
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])

In [21]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=1,)
print("cnn2d_1: \n")
print(cnn2d_1(input_2d_img).shape, "\n")
print(cnn2d_1(input_2d_img))

cnn2d_1: 

torch.Size([1, 1, 1, 8]) 

tensor([[[[0.2948, 0.9233, 1.5518, 2.1804, 2.8089, 3.4374, 4.0660, 4.6945]]]],
       grad_fn=<MkldnnConvolutionBackward>)


In [22]:
cnn2d_2 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=2)
print("cnn2d_2: \n")
print(cnn2d_2(input_2d_img).shape, "\n")
print(cnn2d_2(input_2d_img))

cnn2d_2: 

torch.Size([1, 1, 1, 4]) 

tensor([[[[ 0.0374, -0.9646, -1.9667, -2.9688]]]],
       grad_fn=<MkldnnConvolutionBackward>)


In [23]:
cnn2d_3 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=2, stride=1)
print("cnn2d_3: \n")
print(cnn2d_3(input_2d_img).shape, "\n")
print(cnn2d_3(input_2d_img))

cnn2d_3: 

torch.Size([1, 1, 2, 9]) 

tensor([[[[1.2197, 1.9962, 2.7728, 3.5494, 4.3259, 5.1025, 5.8791, 6.6556,
           7.4322],
          [1.2197, 1.9962, 2.7728, 3.5494, 4.3259, 5.1025, 5.8791, 6.6556,
           7.4322]]]], grad_fn=<MkldnnConvolutionBackward>)


In [24]:
cnn2d_4 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, stride=1)
print("cnn2d_4: \n")
print(cnn2d_4(input_2d_img).shape, "\n")
print(cnn2d_4(input_2d_img))

cnn2d_4: 

torch.Size([1, 5, 1, 8]) 

tensor([[[[ 1.3008,  2.2184,  3.1361,  4.0537,  4.9714,  5.8890,  6.8067,
            7.7243]],

         [[-0.0567, -0.0653, -0.0740, -0.0827, -0.0913, -0.1000, -0.1086,
           -0.1173]],

         [[-0.0568, -0.3175, -0.5783, -0.8391, -1.0999, -1.3607, -1.6215,
           -1.8823]],

         [[-0.2346, -0.2252, -0.2157, -0.2062, -0.1968, -0.1873, -0.1778,
           -0.1684]],

         [[ 1.0794,  1.4350,  1.7906,  2.1463,  2.5019,  2.8575,  3.2131,
            3.5687]]]], grad_fn=<MkldnnConvolutionBackward>)
